name: Stats
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
        
          user: flam3rboy
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          config_twemoji: yes
          repositories: 500
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugin_lines: yes
          plugin_notable: yes
          plugin_traffic: yes
          plugin_stargazers: yes
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
          plugin_habits: yes
          plugin_habits_from: 1000       # Use 200 events to compute habits
          plugin_habits_days: 30        # Keep only events from last 14 days
          plugin_habits_facts: no       # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
