name: Stats
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
        
          user: flam3rboy
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 20
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_projects: yes
          plugin_projects_limit: 20
          plugin_projects_repositories: fosscord/fosscord flam3rboy/discord-bot-client
          plugin_projects_descriptions: yes
          plugin_traffic: yes
          repositories: 500
